apiVersion: v1
kind: Service
metadata:
  name: pihole-active
  namespace: pihole
spec:
  #externalIPs:
  #  - 10.0.0.16
  #  - 10.0.0.20
  #  - 10.0.0.21
  #  - 10.0.0.22
  loadBalancerIP: 10.0.0.104
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: http
      port: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-preview
  namespace: pihole
spec:
  loadBalancerIP: 10.0.0.103
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: http
      port: 80
      protocol: TCP
