---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgB6RmB/c2jAxswrAv2JpWeGhV05cuMApZjU6ofZZS49bnSsF45qOhGac4cDtKHqyyb9r6tym4uNJn3lO6JigPuiHFPnJ12pee9n+GTEIJGuS1Kl4F8C+XPkr0xagDjbDruK/Obxt/DoTdQX4N2cahibKvY+o9RdF4DT0s6xuZk7zsJuGGs7S4fB/LwTBbbGOkB7Ddr7LbcF5BsAyh8q/miiPjMypt4LlYZr1W2e8XZK6lMLw75eypyGeNQNjjMi6wj3sZxJLW07eZuTOKcYbVLcLT82hF1GeYDSvCeaYwqSO8C7jWJgiEP2Jnoilem9zIhTqbi/rtI/YAEEW+WffUXuy5hnumQtq9PJnQ9pw6QaGcGXsp+tDPjqHWlfM2hKI5Ns61N8i8n3ed1I0NlWjkMuyMwrZiLYSjQHeirQWUMfK/UduxMJJKVRc5etpRL+FKjKsQq/3RZnDJ+VSmZPYJsdNKdPA2Y+7CIHHj/VJ36REKkWpCQIDHydJA6PTrJmiG1zictg5riK7Qc+VrS9FgVpqHFe3UeNSZkeCREGiDsttehgj2bt/LrVbSMbD0D+2H2cob1LUST3pFg4YKFYVbRR9ymb70RMFoD51EI9cWw45hleubud0myOaC5A4OM0gDZzPIU/qe3SDVMsY1dnvNtnGKdwLeWx6bFezFqlGgiKLUYeOEcVyXQXzbTjEpQQsTxZMkOHtxNdfuEvlT6ejgwKBhp8
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
