apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: pihole
spec:
  type: LoadBalancer
  selector:
    app: unbound
  ports:
    - name: dns
      port: 5335
      targetPort: 5335
      protocol: UDP
