apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: pihole
spec:
  type: ClusterIP
  selector:
    app: unbound
  ports:
    - name: dns-udp
      port: 5335
      targetPort: 5335
      protocol: UDP
    - name: dns-tcp
      port: 5335
      targetPort: 5335
      protocol: TCP
