apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: unbound
        image: alpinelinux/unbound:latest
        #command: ["unbound"]
        #args: ["-d", "-c", "/etc/unbound/unbound.conf"]
        ports:
          - containerPort: 5335
            protocol: UDP
          - containerPort: 5335
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /etc/unbound
      volumes:
        - name: config
          configMap:
            name: unbound-config
